### ISSUE TITLE
Windows (MSVC) support?

### ISSUE THREAD

**Issue by donalmacc** [nelhage/llama#29]
I saw your blog post on building LLVM in 90 seconds. I work in games using UE4, and the size of UE4 is _roughly_ similar to LLVM, except most compilation happens on windows with MSVC rather than clang. 

Is there some way that MSVC could be supported/

**Comment by nelhage** [comment]
Lambda is Linux-x86_64 only at the moment. I assume there's no plausible way to run MSVC inside Linux? :)

I don't know if Azure has some kind of cloud function equivalent for Windows -- that's the only thing I can think of offhand.

I'm going to close the issue because I don't think Llama itself is likely to get support any time soon, but I'm happy to answer questions if you were to go try to explore doing it on top of some other system.
