### ISSUE TITLE
Install from GitHub directions don't work

### ISSUE THREAD

**Issue by ezyang** [nelhage/llama#30]
I'm not very familiar with golang so I don't know if there's an easy fix.

```
ezyang@devfair040:/scratch/ezyang$ go version                 
go version go1.16.4 linux/amd64                                                 
ezyang@devfair040:/scratch/ezyang$ go install github.com/nelhage/llama/cmd/...
go: warning: "github.com/nelhage/llama/cmd/..." matched no packages
```

**Comment by nelhage** [comment]
Ah, that's my bad -- that line should be `go get …` instead of `go install …`, in order to make it actually fetch the code.

I should maybe remove that option, entirely; right now you mostly need the scripts + Dockerfiles that are in the source checkout, at least to use `llamacc`.

Let me know if either of those options sorts it out!

**Comment by ezyang** [comment]
install from source was fine!
